{{- if .Values.clusterRoles.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "general.fullname" . | quote }}
  labels:
    {{- include "general.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "general.fullname" . | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ include "serviceAccount.name" . | quote }}
    namespace: {{ include "general.namespace" . | quote }}
{{- end }}
