{{- if .Values.clusterRoles.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "general.fullname" . | quote }}
  labels:
    {{- include "general.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["get", "list"]
{{- end }}
