{{- if .Values.podMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "general.fullname" . | quote }}
  namespace: {{ include "general.namespace" . | quote }}
  labels:
    {{- include "general.labels" . | nindent 4 }}
    {{- toYaml .Values.podMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "general.labels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: {{ .Values.container.portName | quote }}
    {{- with .Values.podMonitor }}
      path: {{ .path | quote }}
      interval: {{ .interval | quote }}
      scrapeTimeout: {{ .scrapeTimeout | quote }}
    {{- end }}
{{- end }}
