{{- if .Values.prometheusRules.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "general.fullname" . | quote }}
  labels:
    {{- include "general.labels" . | nindent 4 }}
    {{- toYaml .Values.podMonitor.labels | nindent 4 }}
spec:
  groups:
    - name: {{ include "general.fullname" . | quote }}
      interval: {{ .Values.prometheusRules.interval | quote }}
      rules:
        {{- toYaml .Values.prometheusRules.rules | nindent 8 }}
{{- end }}
