{{- if .Values.github.token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "general.fullname" . | quote }}
  namespace: {{ include "general.namespace" . | quote }}
  labels:
    {{- include "general.labels" . | nindent 4 }}
type: Opaque
data:
  github-token: {{ .Values.github.token | b64enc | quote }}
{{- end }}
