{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serviceAccount.name" . | quote }}
  namespace: {{ include "general.namespace" . | quote }}
  labels:
{{- include "general.labels" . | nindent 4 }}
{{- end }}
