apiVersion: v2
name: kube-inventory
description: A Helm chart for Kubernetes inventory management
type: application
version: 1.0.1
appVersion: "1.0.1"
keywords:
  - kubernetes
  - inventory
  - monitoring
home: https://github.com/srekit/kube-inventory
sources:
  - https://github.com/srekit/kube-inventory
maintainers:
  - name: Emerson Candido
    email: emerson.candido@live.com
